use domain::{AppError, AppInfo, Capabilities, ErrorCode, Platform};
use std::{error::Error, path::PathBuf};
use ts_rs::TS;

fn main() -> Result<(), Box<dyn Error>> {
    let arguments: Vec<_> = std::env::args().skip(1).collect();
    if arguments.iter().any(|argument| argument != "--check") || arguments.len() > 1 {
        return Err("usage: cargo generate-contracts [--check]".into());
    }
    let config = ts_rs::Config::default();
    let declarations = [
        ErrorCode::decl(&config),
        AppError::decl(&config),
        Platform::decl(&config),
        Capabilities::decl(&config),
        AppInfo::decl(&config),
    ];
    let mut output = String::from("// Generated by cargo generate-contracts. Do not edit.\nimport { invoke } from '@tauri-apps/api/core';\n\n");
    for declaration in declarations {
        output.push_str("export ");
        output.push_str(&declaration);
        output.push('\n');
    }
    output.push_str("\nexport function getAppInfo(): Promise<AppInfo> {\n  return invoke<AppInfo>('get_app_info');\n}\n");
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/frontend/src/api/generated.ts");
    if arguments.iter().any(|argument| argument == "--check") {
        if std::fs::read_to_string(path)? != output {
            return Err("IPC contracts are stale; run cargo generate-contracts".into());
        }
    } else {
        std::fs::write(path, output)?;
    }
    Ok(())
}
