use domain::{
    AppError, AppInfo, Capabilities, ErrorCode, Platform, ScanIssue, ScanIssuePage, ScanSession,
    ScanState, StartScanRequest, VolumeInfo,
};
use std::{error::Error, path::PathBuf};
use ts_rs::TS;

fn main() -> Result<(), Box<dyn Error>> {
    let arguments: Vec<_> = std::env::args().skip(1).collect();
    if arguments.iter().any(|argument| argument != "--check") || arguments.len() > 1 {
        return Err("usage: cargo generate-contracts [--check]".into());
    }
    let config = ts_rs::Config::default();
    let declarations = [
        ErrorCode::decl(&config),
        AppError::decl(&config),
        Platform::decl(&config),
        Capabilities::decl(&config),
        AppInfo::decl(&config),
        VolumeInfo::decl(&config),
        ScanState::decl(&config),
        ScanSession::decl(&config),
        StartScanRequest::decl(&config),
        ScanIssue::decl(&config),
        ScanIssuePage::decl(&config),
    ];
    let mut output = String::from("// Generated by cargo generate-contracts. Do not edit.\nimport { invoke, Channel } from '@tauri-apps/api/core';\n\n");
    for declaration in declarations {
        output.push_str("export ");
        // ts-rs places a space after a trailing comma before emitted doc comments.
        // Keep generated files free of trailing whitespace even when they are ignored by Prettier.
        output.push_str(&declaration.replace(", \n", ",\n"));
        output.push('\n');
    }
    output.push_str("\nexport function getAppInfo(): Promise<AppInfo> {\n  return invoke<AppInfo>('get_app_info');\n}\n");
    output.push_str(r#"
export function getVolumes(): Promise<VolumeInfo[]> {
  return invoke<VolumeInfo[]>('get_volumes');
}
export function getScan(scanId: string | null = null): Promise<ScanSession | null> {
  return invoke<ScanSession | null>('get_scan', { scanId });
}
export function startScan(request: StartScanRequest, onProgress: (update: ScanSession) => void): Promise<ScanSession> {
  const channel = new Channel<ScanSession>();
  channel.onmessage = onProgress;
  return invoke<ScanSession>('start_scan', { request, onProgress: channel });
}
export function cancelScan(scanId: string): Promise<ScanSession> {
  return invoke<ScanSession>('cancel_scan', { scanId });
}
export function getScanIssues(scanId: string, afterId: string | null = null): Promise<ScanIssuePage> {
  return invoke<ScanIssuePage>('get_scan_issues', { scanId, afterId });
}
"#);
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/frontend/src/api/generated.ts");
    if arguments.iter().any(|argument| argument == "--check") {
        if std::fs::read_to_string(path)? != output {
            return Err("IPC contracts are stale; run cargo generate-contracts".into());
        }
    } else {
        std::fs::write(path, output)?;
    }
    Ok(())
}
