use domain::{
    AppError, AppInfo, BatchOperationResult, Capabilities, CategorySummary, DirectoryMap,
    DirectoryMapMetric, DirectoryMapNode, DirectoryMapRemainder, DuplicateGroup,
    DuplicateGroupPage, EntryPage, ErrorCode, FileCategory, FileSort, IndexedEntry,
    IndexedEntryKind, OldFile, OldFileCriterion, OldFilePage, Platform, ScanComparison,
    ScanHistoryPage, ScanIssue, ScanIssuePage, ScanSession, ScanState, SnapshotInfo,
    StartScanRequest, VolumeInfo,
};
use std::{error::Error, path::PathBuf};
use ts_rs::TS;

fn main() -> Result<(), Box<dyn Error>> {
    let arguments: Vec<_> = std::env::args().skip(1).collect();
    if arguments.iter().any(|argument| argument != "--check") || arguments.len() > 1 {
        return Err("usage: cargo generate-contracts [--check]".into());
    }
    let config = ts_rs::Config::default();
    let declarations = [
        ErrorCode::decl(&config),
        AppError::decl(&config),
        Platform::decl(&config),
        Capabilities::decl(&config),
        AppInfo::decl(&config),
        VolumeInfo::decl(&config),
        SnapshotInfo::decl(&config),
        ScanState::decl(&config),
        ScanSession::decl(&config),
        StartScanRequest::decl(&config),
        ScanIssue::decl(&config),
        ScanIssuePage::decl(&config),
        IndexedEntryKind::decl(&config),
        IndexedEntry::decl(&config),
        EntryPage::decl(&config),
        DirectoryMapMetric::decl(&config),
        DirectoryMapRemainder::decl(&config),
        DirectoryMapNode::decl(&config),
        DirectoryMap::decl(&config),
        FileCategory::decl(&config),
        FileSort::decl(&config),
        CategorySummary::decl(&config),
        BatchOperationResult::decl(&config),
        OldFile::decl(&config),
        OldFileCriterion::decl(&config),
        OldFilePage::decl(&config),
        ScanHistoryPage::decl(&config),
        ScanComparison::decl(&config),
        DuplicateGroup::decl(&config),
        DuplicateGroupPage::decl(&config),
    ];
    let mut output = String::from("// Generated by cargo generate-contracts. Do not edit.\nimport { invoke, Channel } from '@tauri-apps/api/core';\n\n");
    for declaration in declarations {
        output.push_str("export ");
        // ts-rs places a space after a trailing comma before emitted doc comments.
        // Keep generated files free of trailing whitespace even when they are ignored by Prettier.
        output.push_str(&declaration.replace(", \n", ",\n"));
        output.push('\n');
    }
    output.push_str("\nexport function getAppInfo(): Promise<AppInfo> {\n  return invoke<AppInfo>('get_app_info');\n}\n");
    output.push_str(r#"
export function getVolumes(): Promise<VolumeInfo[]> {
  return invoke<VolumeInfo[]>('get_volumes');
}
export function getScan(scanId: string | null = null): Promise<ScanSession | null> {
  return invoke<ScanSession | null>('get_scan', { scanId });
}
export function startScan(request: StartScanRequest, onProgress: (update: ScanSession) => void): Promise<ScanSession> {
  const channel = new Channel<ScanSession>();
  channel.onmessage = onProgress;
  return invoke<ScanSession>('start_scan', { request, onProgress: channel });
}
export function cancelScan(scanId: string): Promise<ScanSession> {
  return invoke<ScanSession>('cancel_scan', { scanId });
}
export function getScanIssues(scanId: string, afterId: string | null = null): Promise<ScanIssuePage> {
  return invoke<ScanIssuePage>('get_scan_issues', { scanId, afterId });
}
export function getScanRoot(scanId: string): Promise<IndexedEntry> {
  return invoke<IndexedEntry>('get_scan_root', { scanId });
}
export function getChildren(scanId: string, directoryId: string, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_children', { scanId, directoryId, afterId });
}
export function getDirectoryMap(scanId: string, directoryId: string, metric: DirectoryMapMetric, depth: number = 3, maxChildren: number = 8): Promise<DirectoryMap> {
  return invoke<DirectoryMap>('get_directory_map', { scanId, directoryId, metric, depth, maxChildren });
}
export function getLargeFiles(scanId: string, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_large_files', { scanId, afterId });
}
export function getFilteredLargeFiles(scanId: string, minSize: string, category: FileCategory | null, sort: FileSort, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_filtered_large_files', { scanId, minSize, category, sort, afterId });
}
export function getCategories(scanId: string): Promise<CategorySummary[]> {
  return invoke<CategorySummary[]>('get_categories', { scanId });
}
export function getFilesInCategory(scanId: string, category: FileCategory, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_files_in_category', { scanId, category, afterId });
}
export function getOldFiles(scanId: string, criterion: OldFileCriterion, olderThanMs: string, minSize: string | null = null, afterId: string | null = null): Promise<OldFilePage> {
  return invoke<OldFilePage>('get_old_files', { scanId, criterion, olderThanMs, minSize, afterId });
}
export function searchEntries(scanId: string, text: string, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('search_entries', { scanId, text, afterId });
}
export function openEntry(scanId: string, entryId: string): Promise<void> {
  return invoke<void>('open_entry', { scanId, entryId });
}
export function revealEntry(scanId: string, entryId: string): Promise<void> {
  return invoke<void>('reveal_entry', { scanId, entryId });
}
export function moveEntryToTrash(scanId: string, entryId: string): Promise<void> {
  return invoke<void>('move_entry_to_trash', { scanId, entryId });
}
export function moveEntriesToTrash(scanId: string, entryIds: string[]): Promise<BatchOperationResult> {
  return invoke<BatchOperationResult>('move_entries_to_trash', { scanId, entryIds });
}
export function getScanHistory(afterId: string | null = null): Promise<ScanHistoryPage> {
  return invoke<ScanHistoryPage>('get_scan_history', { afterId });
}
export function compareScans(newerScanId: string, olderScanId: string): Promise<ScanComparison> {
  return invoke<ScanComparison>('compare_scans', { newerScanId, olderScanId });
}
export function deleteScanHistory(scanId: string): Promise<void> {
  return invoke<void>('delete_scan_history', { scanId });
}
export function getDuplicateCandidates(afterSize: string | null = null): Promise<DuplicateGroupPage> {
  return invoke<DuplicateGroupPage>('get_duplicate_candidates', { afterSize });
}
export function confirmDuplicates(): Promise<DuplicateGroupPage> {
  return invoke<DuplicateGroupPage>('confirm_duplicates');
}
export function getConfirmedDuplicates(afterId: string | null = null): Promise<DuplicateGroupPage> {
  return invoke<DuplicateGroupPage>('get_confirmed_duplicates', { afterId });
}
"#);
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/frontend/src/api/generated.ts");
    if arguments.iter().any(|argument| argument == "--check") {
        if std::fs::read_to_string(path)? != output {
            return Err("IPC contracts are stale; run cargo generate-contracts".into());
        }
    } else {
        std::fs::write(path, output)?;
    }
    Ok(())
}
