// Generated by cargo generate-contracts. Do not edit.
import { invoke, Channel } from '@tauri-apps/api/core';

export type ErrorCode = "storage_unavailable" | "unsupported_schema" | "invalid_schema" | "internal" | "invalid_target" | "scan_busy" | "scan_not_found" | "invalid_transition" | "size_overflow" | "scan_not_ready" | "launch_failed" | "permission_denied" | "incompatible_scans" | "protected_path" | "entry_changed" | "trash_unavailable";
export type AppError = { code: ErrorCode, user_message_key: string, recoverable: boolean, };
export type Platform = "macos" | "windows" | "linux" | "unsupported";
export type Capabilities = { trash: boolean, permanent_delete: boolean, watcher: boolean, snapshots: boolean, filesystem_details: boolean, allocated_size: boolean, last_access_reliable: boolean, duplicate_hashing: boolean, };
export type AppInfo = { version: string, platform: Platform, schema_version: number, capabilities: Capabilities, };
export type VolumeInfo = { name: string,
/**
 * None means the native mount point cannot be represented in the path input.
 */
mount_point: string | null, filesystem: string, total_bytes: string, available_bytes: string, };
export type SnapshotInfo = { id: string, name: string, created_at_ms: string, logical_size: string | null, exclusive_size: string | null, };
export type ScanState = "created" | "preparing" | "scanning" | "finalizing" | "completed" | "partial" | "cancelling" | "cancelled" | "failed" | "interrupted";
export type ScanSession = { id: string, root_path: string, state: ScanState, files_count: string,
/**
 * Includes the selected root directory.
 */
directories_count: string, symlinks_count: string, skipped_count: string, logical_size: string,
/**
 * None when the current platform cannot report allocated filesystem blocks.
 */
allocated_size: string | null, errors_count: string, started_at_ms: string, finished_at_ms: string | null, failure: AppError | null, };
export type StartScanRequest = { root_path: string, };
export type ScanIssue = { path: string, code: string, operation: string, };
export type ScanIssuePage = { items: Array<ScanIssue>, next_cursor: string | null, };
export type IndexedEntryKind = "file" | "directory" | "symlink" | "other";
export type IndexedEntry = { id: string, parent_id: string | null, name: string, path: string, kind: IndexedEntryKind, logical_size: string,
/**
 * The complete descendant size for directories, otherwise the file size.
 */
aggregate_size: string, };
export type EntryPage = { items: Array<IndexedEntry>, next_cursor: string | null, };
export type FileCategory = "video" | "images" | "audio" | "documents" | "archives" | "applications" | "development" | "disk_images" | "databases" | "other";
export type FileSort = "size_desc" | "modified_desc" | "name_asc";
export type CategorySummary = { category: FileCategory, files_count: string, logical_size: string, };
export type BatchOperationResult = { moved_entry_ids: Array<string>, failed_entry_ids: Array<string>, };
export type OldFile = { entry: IndexedEntry, timestamp_ms: string, };
export type OldFileCriterion = "modified" | "created" | "accessed";
export type OldFilePage = { items: Array<OldFile>, next_cursor: string | null, };
export type ScanHistoryPage = { items: Array<ScanSession>, next_cursor: string | null, };
export type ScanComparison = { newer_scan_id: string, older_scan_id: string, files_delta: string, directories_delta: string, logical_size_delta: string, added_files_count: string, removed_files_count: string, modified_files_count: string, moved_files_count: string, };
export type DuplicateGroup = { size: string, files_count: string, reclaimable_size: string, };
export type DuplicateGroupPage = { items: Array<DuplicateGroup>, next_cursor: string | null, };

export function getAppInfo(): Promise<AppInfo> {
  return invoke<AppInfo>('get_app_info');
}

export function getVolumes(): Promise<VolumeInfo[]> {
  return invoke<VolumeInfo[]>('get_volumes');
}
export function getScan(scanId: string | null = null): Promise<ScanSession | null> {
  return invoke<ScanSession | null>('get_scan', { scanId });
}
export function startScan(request: StartScanRequest, onProgress: (update: ScanSession) => void): Promise<ScanSession> {
  const channel = new Channel<ScanSession>();
  channel.onmessage = onProgress;
  return invoke<ScanSession>('start_scan', { request, onProgress: channel });
}
export function cancelScan(scanId: string): Promise<ScanSession> {
  return invoke<ScanSession>('cancel_scan', { scanId });
}
export function getScanIssues(scanId: string, afterId: string | null = null): Promise<ScanIssuePage> {
  return invoke<ScanIssuePage>('get_scan_issues', { scanId, afterId });
}
export function getScanRoot(scanId: string): Promise<IndexedEntry> {
  return invoke<IndexedEntry>('get_scan_root', { scanId });
}
export function getChildren(scanId: string, directoryId: string, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_children', { scanId, directoryId, afterId });
}
export function getLargeFiles(scanId: string, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_large_files', { scanId, afterId });
}
export function getFilteredLargeFiles(scanId: string, minSize: string, category: FileCategory | null, sort: FileSort): Promise<EntryPage> {
  return invoke<EntryPage>('get_filtered_large_files', { scanId, minSize, category, sort });
}
export function getCategories(scanId: string): Promise<CategorySummary[]> {
  return invoke<CategorySummary[]>('get_categories', { scanId });
}
export function getFilesInCategory(scanId: string, category: FileCategory, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('get_files_in_category', { scanId, category, afterId });
}
export function getOldFiles(scanId: string, criterion: OldFileCriterion, olderThanMs: string, minSize: string | null = null, afterId: string | null = null): Promise<OldFilePage> {
  return invoke<OldFilePage>('get_old_files', { scanId, criterion, olderThanMs, minSize, afterId });
}
export function searchEntries(scanId: string, text: string, afterId: string | null = null): Promise<EntryPage> {
  return invoke<EntryPage>('search_entries', { scanId, text, afterId });
}
export function openEntry(scanId: string, entryId: string): Promise<void> {
  return invoke<void>('open_entry', { scanId, entryId });
}
export function revealEntry(scanId: string, entryId: string): Promise<void> {
  return invoke<void>('reveal_entry', { scanId, entryId });
}
export function moveEntryToTrash(scanId: string, entryId: string): Promise<void> {
  return invoke<void>('move_entry_to_trash', { scanId, entryId });
}
export function moveEntriesToTrash(scanId: string, entryIds: string[]): Promise<BatchOperationResult> {
  return invoke<BatchOperationResult>('move_entries_to_trash', { scanId, entryIds });
}
export function getScanHistory(afterId: string | null = null): Promise<ScanHistoryPage> {
  return invoke<ScanHistoryPage>('get_scan_history', { afterId });
}
export function compareScans(newerScanId: string, olderScanId: string): Promise<ScanComparison> {
  return invoke<ScanComparison>('compare_scans', { newerScanId, olderScanId });
}
export function deleteScanHistory(scanId: string): Promise<void> {
  return invoke<void>('delete_scan_history', { scanId });
}
export function getDuplicateCandidates(afterSize: string | null = null): Promise<DuplicateGroupPage> {
  return invoke<DuplicateGroupPage>('get_duplicate_candidates', { afterSize });
}
export function confirmDuplicates(): Promise<DuplicateGroupPage> {
  return invoke<DuplicateGroupPage>('confirm_duplicates');
}
