// Generated by cargo generate-contracts. Do not edit.
import { invoke, Channel } from '@tauri-apps/api/core';

export type ErrorCode = "storage_unavailable" | "unsupported_schema" | "invalid_schema" | "internal" | "invalid_target" | "scan_busy" | "scan_not_found" | "invalid_transition" | "size_overflow";
export type AppError = { code: ErrorCode, user_message_key: string, recoverable: boolean, };
export type Platform = "macos" | "windows" | "linux" | "unsupported";
export type Capabilities = { trash: boolean, permanent_delete: boolean, watcher: boolean, snapshots: boolean, filesystem_details: boolean, allocated_size: boolean, last_access_reliable: boolean, duplicate_hashing: boolean, };
export type AppInfo = { version: string, platform: Platform, schema_version: number, capabilities: Capabilities, };
export type VolumeInfo = { name: string,
/**
 * None means the native mount point cannot be represented in the path input.
 */
mount_point: string | null, filesystem: string, total_bytes: string, available_bytes: string, };
export type ScanState = "created" | "preparing" | "scanning" | "finalizing" | "completed" | "partial" | "cancelling" | "cancelled" | "failed" | "interrupted";
export type ScanSession = { id: string, root_path: string, state: ScanState, files_count: string,
/**
 * Includes the selected root directory.
 */
directories_count: string, symlinks_count: string, skipped_count: string, logical_size: string,
/**
 * Unknown until native allocated-size providers are implemented.
 */
allocated_size: string | null, errors_count: string, started_at_ms: string, finished_at_ms: string | null, failure: AppError | null, };
export type StartScanRequest = { root_path: string, };
export type ScanIssue = { path: string, code: string, operation: string, };
export type ScanIssuePage = { items: Array<ScanIssue>, next_cursor: string | null, };

export function getAppInfo(): Promise<AppInfo> {
  return invoke<AppInfo>('get_app_info');
}

export function getVolumes(): Promise<VolumeInfo[]> {
  return invoke<VolumeInfo[]>('get_volumes');
}
export function getScan(scanId: string | null = null): Promise<ScanSession | null> {
  return invoke<ScanSession | null>('get_scan', { scanId });
}
export function startScan(request: StartScanRequest, onProgress: (update: ScanSession) => void): Promise<ScanSession> {
  const channel = new Channel<ScanSession>();
  channel.onmessage = onProgress;
  return invoke<ScanSession>('start_scan', { request, onProgress: channel });
}
export function cancelScan(scanId: string): Promise<ScanSession> {
  return invoke<ScanSession>('cancel_scan', { scanId });
}
export function getScanIssues(scanId: string, afterId: string | null = null): Promise<ScanIssuePage> {
  return invoke<ScanIssuePage>('get_scan_issues', { scanId, afterId });
}
