// Generated by cargo generate-contracts. Do not edit.
import { invoke } from '@tauri-apps/api/core';

export type ErrorCode = "storage_unavailable" | "unsupported_schema" | "invalid_schema" | "internal";
export type AppError = { code: ErrorCode, user_message_key: string, recoverable: boolean, };
export type Platform = "macos" | "windows" | "linux" | "unsupported";
export type Capabilities = { trash: boolean, permanent_delete: boolean, watcher: boolean, snapshots: boolean, filesystem_details: boolean, allocated_size: boolean, last_access_reliable: boolean, duplicate_hashing: boolean, };
export type AppInfo = { version: string, platform: Platform, schema_version: number, capabilities: Capabilities, };

export function getAppInfo(): Promise<AppInfo> {
  return invoke<AppInfo>('get_app_info');
}
