[package]
name = "filesystem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
sysinfo = { version = "0.38.4", default-features = false, features = ["disk"] }

[dev-dependencies]
tempfile.workspace = true
