[package]
name = "desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
domain.workspace = true
filesystem.workspace = true
storage.workspace = true
services.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tauri-plugin-wdio-webdriver = { version = "1", optional = true }
tauri-plugin-wdio = { version = "1", optional = true }

[features]
custom-protocol = ["tauri/custom-protocol"]
e2e = ["dep:tauri-plugin-wdio", "dep:tauri-plugin-wdio-webdriver"]

[dev-dependencies]
tauri = { version = "2", features = ["test"] }
serde_json.workspace = true
tempfile.workspace = true
