[package]
name = "services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
filesystem.workspace = true
storage.workspace = true

scanner.workspace = true
analyzer.workspace = true
tracing.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
rusqlite.workspace = true
